[package]
name = "unroll"
version = "0.1.5"
edition = "2024"

[lib]
proc-macro = true

[dependencies]
syn = { version = "2.0", default-features = false, features = ["proc-macro", "parsing", "full", "printing"] }
quote = "1.0"

[dev-dependencies]
criterion = "0.3"
rand = "0.8"
