[package]
name = "std"
version = "0.1.0"
edition = "2021"

[lints.rust]
dead_code = "allow"
static_mut_refs = "allow"

[build]
target = "x86_64-unknown-none"

[lib]
crate-type = ["rlib"]

[dependencies]

[features]
test_includes = []

[profile.dev]
debug = true

[profile.release]
debug = true
